// Generated by CoffeeScript 1.4.0
(function() {

  Meteor.log = {
    message: function(message, level, params) {
      if (params == null) {
        params = {};
      }
      if ((typeof __ !== "undefined" && __ !== null) && _.isFunction(__)) {
        message = __("services.log." + level, {
          msg: __(message, params)
        });
      } else {
        message = level + ': ' + message;
      }
      return Meteor._debug(message);
    },
    error: function(message, params) {
      if (params == null) {
        params = {};
      }
      return this.message(message, 'error', params);
    },
    warning: function(message, params) {
      if (params == null) {
        params = {};
      }
      return this.message(message, 'warning', params);
    },
    info: function(message, params) {
      if (params == null) {
        params = {};
      }
      return this.message(message, 'info', params);
    },
    "throw": function(message, params) {
      if (params == null) {
        params = {};
      }
      throw __(message, params);
    }
  };

  if (Meteor.i18nMessages != null) {
    Meteor.i18nMessages.log = {
      error: {
        en: 'Error: {{msg}}',
        de: 'Fehler: {{msg}}',
        pt: 'Erro: {{msg}}'
      },
      info: 'Info: {{msg}}',
      warning: {
        en: 'Warning: {{msg}}',
        de: 'Vorsicht: {{msg}}',
        pt: 'Cuidado: {{msg}}'
      }
    };
  }

}).call(this);
