// Generated by CoffeeScript 1.4.0
(function() {

  Meteor.log = function(message, params, level) {
    if (params == null) {
      params = {};
    }
    if (level == null) {
      level = 'info';
    }
    if (_.isString(params)) {
      level = params;
      params = {};
    }
    if ((typeof __ !== "undefined" && __ !== null) && _.isFunction(__)) {
      message = __("_meteor.logger." + level, {
        msg: __(message, params)
      });
    } else {
      message = level + ': ' + message;
    }
    return Meteor._debug(message);
  };

  _.extend(Meteor.log, {
    error: function(message, params) {
      if (params == null) {
        params = {};
      }
      return this(message, params, 'error');
    },
    warning: function(message, params) {
      if (params == null) {
        params = {};
      }
      return this(message, params, 'warning');
    },
    info: function(message, params) {
      if (params == null) {
        params = {};
      }
      return this(message, params, 'info');
    },
    "throw": function(message, params) {
      if (params == null) {
        params = {};
      }
      throw new Error(__(message, params));
    }
  });

  if (Meteor.i18nMessages == null) {
    Meteor.i18nMessages = {};
  }

  if (Meteor.i18nMessages._meteor == null) {
    Meteor.i18nMessages._meteor = {};
  }

  Meteor.i18nMessages._meteor.logger = {
    error: {
      en: 'Error: {{msg}}',
      de: 'Fehler: {{msg}}',
      pt: 'Erro: {{msg}}'
    },
    info: 'Info: {{msg}}',
    warning: {
      en: 'Warning: {{msg}}',
      de: 'Vorsicht: {{msg}}',
      pt: 'Cuidado: {{msg}}'
    }
  };

}).call(this);
